### ISSUE TITLE
[Bug]: Service UUIDs no longer found in advertismentData

### ISSUE THREAD

**Issue by LipJ01** [boskokg/flutter_blue_plus#672]
### Requirements

- [X] I've looked at the README 'Common Problems' section

### Have you checked this problem on the example app?

No

### FlutterBluePlus Version

1.27.1-1.28.7

### Flutter Version

3.14.0

### What OS?

iOS

### OS Version

17.1.1

### Bluetooth Module

Nordic nRF52833

### What is your problem?

The following code snippet no longer works the same. Prior to 1.27.1 This will find the serviceUUID that my ble device is advertising. Post 1.27.0 I always have empty serviceUUID field in advertismentData.

```
FlutterBluePlus.scanResults.listen((results) {
    for (ScanResult r in results) {
        print('BLE: ${r.device.platformName} GATT table: ${r.advertisementData}');
    }
}
```

### Logs

```shell
Previously:
BLE: MicroNode_123456_v6.5.13 GATT table: AdvertisementData{localName: MicroNode_123456_v6.5.13, txPowerLevel: null, connectable: true, manufacturerData: {}, serviceData: {}, serviceUuids: [8D53DC1D-1DB7-4CD3-868B-8A527460AA84]}

Now:
BLE: MicroNode_123456_v6.5.13 GATT table: AdvertisementData{localName: MicroNode_123456_v6.5.13, txPowerLevel: null, connectable: true, manufacturerData: {}, serviceData: {}, serviceUuids: []}
```

**Comment by chipweinberger** [comment]
try master branch

**Comment by chipweinberger** [comment]
fixed in 1.28.8

**Comment by LipJ01** [comment]
I've just tested. This is NOT fixed. Please reopen issue and perhaps slow down the releases a tad.

**Comment by sprimm98** [comment]
Hi! This problem also exists in version 1.29.11. Please reopen this thread.

**Comment by sprimm98** [comment]
Thanks for replying. For now, I'll set `continuousUpdates` back to `true` for scanning as this seems to solve the problem. I don't think there is a problem with that snippet above, maybe it's device related.

**Comment by chipweinberger** [comment]
its related to this bug: https://github.com/boskokg/flutter_blue_plus/issues/710#issuecomment-1837140039
